#!/usr/bin/env python3
"""Generate oath/plugin_assets.go from plugin/.

SINGLE SOURCE, GENERATED COPY — the same arrangement the website docs use. The
plugin content lives in plugin/ where it can be read, reviewed and diffed as
ordinary markdown; the kernel needs it compiled in so an installed binary works
with no repository present. Duplicating it by hand would drift, so it is generated
and the drift is gated (`make check-plugin-assets`).

Usage: gen-plugin-assets.py [--check]
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "oath" / "plugin_assets.go"

ASSETS = [
    ("skillRegistryFirst", "plugin/skills/registry-first/SKILL.md"),
    ("agentSearch", "plugin/agents/oath-search.md"),
    ("agentProperties", "plugin/agents/oath-properties.md"),
    ("agentImplement", "plugin/agents/oath-implement.md"),
    ("agentAdversary", "plugin/agents/oath-adversary.md"),
    ("codexAgents", "plugin/codex/AGENTS.md"),
]


def render():
    parts = ["package main\n\n",
             "// GENERATED by scripts/gen-plugin-assets.py from plugin/. Do not edit.\n",
             "// The markdown in plugin/ is the single source; `make check-plugin-assets`\n",
             "// fails if this file drifts from it.\n\n"]
    for var, rel in ASSETS:
        body = (ROOT / rel).read_text()
        # Interpreted string literals, not raw: the markdown is full of backticks
        # (tool names, code fences), and a raw literal cannot contain one.
        esc = body.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
        parts.append(f'// {var} is {rel}.\nconst {var} = "{esc}"\n\n')
    return "".join(parts)


def gofmt(text):
    """Format through gofmt so WRITE and CHECK compare the same bytes.

    Without this the check compared un-formatted rendered output against the
    formatted file on disk and reported drift on every run — a gate that always
    fails teaches people to ignore it, which is worse than no gate.
    """
    r = subprocess.run(["gofmt"], input=text, capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else text


def main():
    text = gofmt(render())
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("plugin assets are STALE: oath/plugin_assets.go does not match plugin/.")
            print("Run `make plugin-assets` and commit the result.")
            return 1
        print("plugin assets in sync ✓")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} from {len(ASSETS)} source files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
