package main

import (
	"strings"
	"testing"
)

// `oath build --emit-source` hands back the backend source a compiler would have
// assembled and does NOT invoke the toolchain, so a consumer can SEE the lowering
// — e.g. that a str-map became a native map, not the O(N) structural fallback —
// which a normal build hides in a temp directory it deletes. This pins that
// emitSourceFor (the body of the flag) produces native str-map source for both
// backends. It needs neither go nor clang: it only calls the emitters.
func TestEmitSourceShowsNativeStrMap(t *testing.T) {
	st := newStore(t)
	strMapPrelude(t, st)
	strMapModel(t, st)
	// A valid CLI entry — (List Str) -> Str — that exercises the native str-map
	// increment path and returns a key (a Str), so no rendering helper is needed.
	put(t, st, `(defn sm-probe [] [(args (List Str))] Str
		(match (str-map-keys (str-map-insert "x" 1 str-map-empty))
			((Nil) "empty") ((Cons h t) h)))`)
	markVerified(t, st, "sm-probe")
	prog, err := planProgram(st, "sm-probe")
	if err != nil {
		t.Fatalf("planProgram: %v", err)
	}

	goSrc, err := emitSourceFor(st, prog, "go")
	if err != nil {
		t.Fatalf("emit go source: %v", err)
	}
	if !strings.HasPrefix(goSrc, "// Generated by oath build") {
		t.Errorf("emitted Go is missing the generated header (got %.40q)", goSrc)
	}
	for _, want := range []string{"smapInsert", "smapEmpty", "smapKeys"} {
		if !strings.Contains(goSrc, want) {
			t.Errorf("Go --emit-source did not show native helper %q — str-map fell back to structural", want)
		}
	}

	llSrc, err := emitSourceFor(st, prog, "llvm")
	if err != nil {
		t.Fatalf("emit llvm source: %v", err)
	}
	if !strings.Contains(strings.ToLower(llSrc), "strmap") {
		t.Error("LLVM --emit-source did not show the native str-map lowering")
	}
}
