package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// #187: authoring-layer dependency resolution, entirely OUTSIDE identity. A .oath
// source references bare names that resolve against whatever ambient store is
// active at put time, with a late/silent failure. `oath resolve` records the
// intention — which external names, at which hashes — in a lockfile, and
// `oath put --lock` verifies the store against it BEFORE elaborating, turning the
// ambient binding into a checked one. Nothing here changes what a Def hashes to:
// the lock guards resolution, it never participates in it.

const oathLockFormat = "oath-lock/1"

// oathLock is the resolved dependency manifest for one source file. Dependencies
// are the DIRECT external names the source references (checked by name at
// put --lock); Closure is the full transitive object closure (fetched so
// elaboration can typecheck). It is generated by `oath resolve` and may be edited
// by hand to pin or disambiguate.
type oathLock struct {
	Format       string            `json:"format"`
	File         string            `json:"file"`
	Dependencies map[string]string `json:"dependencies"` // direct external name -> hash
	Closure      []string          `json:"closure"`      // transitive object hashes, sorted
}

// seedStore is a throwaway IN-MEMORY copy of `from`, so a batch can be elaborated
// (with its same-batch references resolving) without mutating the source store. It
// is explicitly memory-backed rather than OpenStore(dir): OpenStore honours
// OATH_BACKEND, so on a cloud-tagged binary a scratch store would silently BE the
// real cloud store, and elaboration would write objects and repoint names into it
// bypassing every gate. In-memory also needs no temp directory to clean up.
func seedStore(from *Store) (*Store, error) {
	tmp, err := newStoreWithBackend(newMemBackend(), "resolve-scratch")
	if err != nil {
		return nil, err
	}
	if err := copyStore(from, tmp); err != nil {
		return nil, err
	}
	return tmp, nil
}

// copyStore copies every object and name binding from one store into another.
func copyStore(from, into *Store) error {
	for _, h := range from.AllHashes() {
		d, err := from.GetDef(h)
		if err != nil {
			continue
		}
		m, _ := from.GetMeta(h)
		if m == nil {
			m = &Meta{}
		}
		if _, err := into.StoreObject(d, m); err != nil {
			return err
		}
	}
	for name, h := range from.Names() {
		if _, err := into.Repoint(name, h); err != nil {
			return err
		}
	}
	return nil
}

// registryFetcher builds the Store.fetcher for `oath resolve --remote`: on a name
// miss it resolves the name at the registry, pulls the object and its transitive
// closure (each re-verified by hash in remoteObject), stores them into `into`, and
// binds the name. clientSigner must already be set for remoteBinding.
//
// The Store.fetcher contract is bool, but a registry error (unreachable, auth
// refused, no `object` tool, a content-address mismatch, a dependency that does not
// typecheck) must not vanish into a downstream "unknown name". So the FIRST such
// error is captured and returned by the accompanying accessor, which cmdResolve
// surfaces when elaboration then fails. A name the registry genuinely does not hold
// (no binding) is NOT an error — an honest "unknown name" is the right report.
func registryFetcher(url string, s Signer, into *Store) (func(string) bool, func() error) {
	var firstErr error
	note := func(err error) { // remember the first real failure
		if firstErr == nil {
			firstErr = err
		}
	}
	var fetchClosure func(hash string) error
	fetchClosure = func(hash string) error {
		if _, err := into.GetDef(hash); err == nil {
			return nil // already present
		}
		d, m, err := remoteObject(context.Background(), url, s, hash)
		if err != nil {
			return err
		}
		// Fetch DEPENDENCIES FIRST, then typecheck this object against them before
		// caching it. remoteObject verified the hash, but a hash-consistent yet
		// ill-formed Def from a nonconforming registry must not be stored unchecked
		// — GetDef would then hand it out bypassing the kernel's admission. checkDef
		// needs the deps present, hence the bottom-up order.
		for dep := range collectDeps(d) {
			if err := fetchClosure(dep); err != nil {
				return err
			}
		}
		if err := checkDef(into, d); err != nil {
			return fmt.Errorf("registry object #%s does not typecheck: %w", shortHash(hash), err)
		}
		if _, err := into.StoreObject(d, m); err != nil {
			return err
		}
		return nil
	}
	fetch := func(name string) bool {
		hash, err := remoteBinding(url, name)
		if err != nil {
			note(fmt.Errorf("resolving %q at the registry: %w", name, err))
			return false
		}
		if hash == noParent || hash == "" {
			return false // the registry genuinely has no such name — not an error
		}
		if err := fetchClosure(hash); err != nil {
			note(fmt.Errorf("fetching %q: %w", name, err))
			return false
		}
		if _, err := into.Repoint(name, hash); err != nil {
			note(err)
			return false
		}
		return true
	}
	return fetch, func() error { return firstErr }
}

// elaborateInto elaborates each top-level form against tmp (ELABORATION ONLY — no
// verification, no journalling) in order, storing each so a later same-batch form
// can resolve it. It returns the batch's object hashes and the DIRECT EXTERNAL
// dependencies (surface name -> hash).
//
// The external classification is per resolution and by PRIOR-BATCH HASH, which is
// what makes it correct on two edge cases a coarser rule misses. A name is external
// for a form iff it resolved to a hash NO EARLIER FORM produced — so an early form's
// reference to an ambient `foo` is captured as external even when a later form
// redeclares `foo` (order-dependent shadowing), and a reference to a prior form is
// same-batch even when that form is byte-identical to an external definition (a hash
// collision). Names are captured (not reconstructed from hashes) because Resolve and
// FindCtor both log the surface name the source actually used.
func elaborateInto(tmp *Store, src string) (map[string]string, error) {
	forms, err := parseForms(src)
	if err != nil {
		return nil, err
	}
	priorNames := map[string]bool{} // names DECLARED by earlier forms in this batch
	external := map[string]string{} // direct external dependency: surface name -> hash
	for _, f := range forms {
		if f.K != "list" || len(f.Kids) == 0 {
			return nil, fmt.Errorf("top-level form must be (defn ...) or (data ...)")
		}
		tmp.resolveLog = map[string]string{}
		var d *Def
		var m *Meta
		switch {
		case f.Kids[0].isSym("defn"):
			d, m, err = elabFunc(tmp, f)
		case f.Kids[0].isSym("data"):
			d, m, err = elabData(tmp, f)
		default:
			tmp.resolveLog = nil
			return nil, fmt.Errorf("top-level form must be (defn ...) or (data ...), got %q", f.Kids[0].Sym)
		}
		logged := tmp.resolveLog
		tmp.resolveLog = nil
		if err != nil {
			return nil, err
		}
		// A resolution is EXTERNAL iff its surface name was not declared by an
		// EARLIER form. By NAME, not by hash: a name is a same-batch reference only
		// when this batch bound it first, regardless of whether the object it
		// resolves to happens to equal an ambient definition under another name
		// (structurally identical aliases are supported, CLAUDE.md). Order matters —
		// an early reference to an ambient `foo` stays external even if a later form
		// redeclares `foo`.
		for name, rh := range logged {
			if !priorNames[name] {
				external[name] = rh
			}
		}
		h, err := tmp.StoreObject(d, m)
		if err != nil {
			return nil, err
		}
		if m.Name != "" {
			priorNames[m.Name] = true
			for _, cn := range m.CtorNames { // a data form also declares its constructors
				priorNames[cn] = true
			}
			if _, err := tmp.Repoint(m.Name, h); err != nil {
				return nil, err
			}
		}
	}
	return external, nil
}

// externalClosure elaborates src against `from` (which must hold its dependencies)
// and returns the direct external dependencies (surface name -> hash) plus the full
// transitive object closure of those hashes (so a fresh store can typecheck them).
func externalClosure(from *Store, src string) (map[string]string, []string, error) {
	elab, err := seedStore(from)
	if err != nil {
		return nil, nil, err
	}
	return computeExternal(elab, src)
}

// computeExternal elaborates src IN `elab` — a scratch store that resolves every
// dependency, whether by being seeded from a local store or by an on-demand
// registry fetcher — and returns the direct external names and transitive closure.
// The fetched/seeded objects are left in `elab` for the caller to copy out.
func computeExternal(elab *Store, src string) (map[string]string, []string, error) {
	direct, err := elaborateInto(elab, src)
	if err != nil {
		return nil, nil, err
	}
	// Transitive closure of the direct external hashes. No batch exclusion: the
	// roots are external NAMES, whose closures lie entirely in `from`, so a batch
	// object is never reached — and a direct external whose hash happens to equal a
	// later batch form's is still fetched, as it must be for an earlier reference.
	closure := map[string]bool{}
	var visit func(string)
	visit = func(h string) {
		if closure[h] {
			return
		}
		closure[h] = true
		d, err := elab.GetDef(h)
		if err != nil {
			return
		}
		for dep := range collectDeps(d) {
			visit(dep)
		}
	}
	for _, h := range direct {
		visit(h)
	}
	hs := make([]string, 0, len(closure))
	for h := range closure {
		hs = append(hs, h)
	}
	sort.Strings(hs)
	return direct, hs, nil
}

// cmdHydrate is the inverse of `oath resolve`: it takes a LOCKFILE plus an object
// source and populates the target store to match the lock. `resolve` writes a lock
// FROM a store; `hydrate` writes a store FROM a lock — closing the gap the
// resolve-consumer flywheel surfaced, where a consumer holding the lock (a
// checkable record of exactly which objects it needs) had no command to obtain
// them. Nothing is computed: the closure is already enumerated in the lock, so
// hydrate FETCHES it and re-verifies every object by hash.
//
// It is transactional against VALIDATION failure: the whole closure is fetched and
// typechecked into an in-memory scratch first, and the target is written only once
// the lock's claims hold — so a source missing an object, a content-address
// mismatch, or an unclosed lock leaves the target untouched rather than
// half-populated. It is NOT transactional against a mid-commit I/O failure (a
// backend write failing after some objects are written); that surfaces as an error
// and may leave a partial store, the same as any other store write.
func cmdHydrate(target *Store, lockFile, fromDir, remoteURL, keyFile string) {
	lock, err := readLock(lockFile)
	if err != nil {
		fail(err)
	}
	hydrateLockInto(target, lock, fromDir, remoteURL, keyFile, "hydrate")
	fmt.Printf("hydrated %d object(s), bound %d name(s) into %s\n", len(lock.Closure), len(lock.Dependencies), target.Root)
}

// hydrateLockInto is the shared core of `oath hydrate` and `oath clone`: it fetches
// the lock's closure by hash from the named source, verifies it is closed and
// content-addressed, commits it, and binds the direct names. It does NOT print — the
// caller reports, because `hydrate` and `clone` frame the same work differently. `op`
// is the verb used in its refusal messages (hydrate/clone).
func hydrateLockInto(target *Store, lock oathLock, fromDir, remoteURL, keyFile, op string) {
	// This WRITES objects and binds names — the same hazard as `resolve --from`,
	// refused the same way: the canonical corpus must not be polluted, and a cloud
	// store is shared, so a write into it would bypass gates and journalling.
	if os.Getenv("OATH_BACKEND") == "cloud" {
		fail(fmt.Errorf("refusing to %s into a cloud-backed store: %s into a local working store (OATH_STORE=$(mktemp -d))", op, op))
	}
	if isCanonicalStore(target.Root) {
		fail(fmt.Errorf("refusing to %s into the canonical corpus %q: %s into a local working store (OATH_STORE=$(mktemp -d)), not the tracked store", op, target.Root, op))
	}
	switch {
	case fromDir == "" && remoteURL == "":
		fail(fmt.Errorf("%s needs an object source: --from <store> or --remote <url> --key <file>", op))
	case fromDir != "" && remoteURL != "":
		fail(fmt.Errorf("--from and --remote are two sources; give one"))
	}

	// The source is a by-HASH object provider. Fetching by hash rather than by name
	// reproduces the pinned closure regardless of whether the source's name bindings
	// have since moved — which is the whole reason a lock pins hashes.
	var get func(hash string) (*Def, *Meta, error)
	switch {
	case remoteURL != "":
		signer, err := resolveSigner(keyFile, "")
		if err != nil {
			fail(fmt.Errorf("oath %s --remote authenticates every read; pass --key <file>: %w", op, err))
		}
		clientSigner = signer
		get = func(h string) (*Def, *Meta, error) {
			return remoteObject(context.Background(), remoteURL, signer, h)
		}
	case fromDir != "":
		// Explicit FILESYSTEM backend: OpenStore honours OATH_BACKEND, so on a
		// cloud-tagged binary `--from /local/store` would read the cloud store.
		be, err := openFSBackend(fromDir)
		if err != nil {
			fail(err)
		}
		fromStore, err := newStoreWithBackend(be, fromDir)
		if err != nil {
			fail(err)
		}
		get = func(h string) (*Def, *Meta, error) {
			d, err := fromStore.GetDef(h)
			if err != nil {
				return nil, nil, err
			}
			m, _ := fromStore.GetMeta(h)
			if m == nil {
				m = &Meta{}
			}
			return d, m, nil
		}
	}

	// Fetch EXACTLY the lock's closure into an in-memory scratch — no more. The
	// closure is the WHOLE universe hydrate will commit, so it must also be the whole
	// universe it typechecks against. Recursing into the source via collectDeps would
	// let an INCOMPLETE lock — one omitting a transitive dependency the source still
	// holds — pull the missing object into scratch, pass checkDef, and then commit
	// only lock.Closure: the target would reference an uncommitted hash while hydrate
	// reported success. So every object is stored first (StoreObject does not
	// typecheck), then each is checked against scratch, which holds ONLY the listed
	// closure. A dependency outside the closure is absent, so checkDef fails and the
	// unclosed lock is refused — never silently completed from the source.
	scratch, err := newStoreWithBackend(newMemBackend(), "hydrate-scratch")
	if err != nil {
		fail(err)
	}
	for _, h := range lock.Closure {
		d, m, err := get(h)
		if err != nil {
			fail(fmt.Errorf("fetching %s: %w", hydrateFetchLabel(lock, h), err))
		}
		if got := hashDef(d); got != h {
			fail(fmt.Errorf("source returned #%s for requested %s — content-address mismatch", shortHash(got), hydrateFetchLabel(lock, h)))
		}
		if _, err := scratch.StoreObject(d, m); err != nil {
			fail(err)
		}
	}
	for _, h := range lock.Closure {
		d, err := scratch.GetDef(h) // cached by StoreObject above; no re-check here
		if err != nil {
			fail(err)
		}
		if err := checkDef(scratch, d); err != nil {
			fail(fmt.Errorf("lock closure is not closed: object #%s references a hash the closure omits: %w", shortHash(h), err))
		}
	}

	// Every direct dependency the lock names must be among the objects we fetched.
	for name, h := range lock.Dependencies {
		if _, err := scratch.GetDef(h); err != nil {
			fail(fmt.Errorf("lock names dependency %q at #%s, absent from the fetched closure (corrupt lock?)", name, shortHash(h)))
		}
	}

	// Commit: the closure verified. Copy every object into the target, then bind the
	// direct names — objects first, so a name never points at an absent object. Only
	// the DIRECT names are bound; transitive objects are reachable by hash, exactly as
	// `resolve --from` leaves them.
	//
	// When the target ALREADY holds an object (the non-empty-target case), preserve
	// BOTH sides' naming by union rather than letting StoreObject's merge run:
	// StoreObject is written for single-name source elaboration and DISCARDS an
	// incoming Aliases map, so a lock binding a non-primary alias would lose that
	// alias's constructor vocabulary and the later `put --lock` would fail on an
	// unknown constructor. On a fresh target StoreObject stores the source meta as-is
	// (no prev), which already keeps every source alias.
	for _, h := range lock.Closure {
		d, err := scratch.GetDef(h)
		if err != nil {
			fail(err)
		}
		sm, _ := scratch.GetMeta(h)
		if sm == nil {
			sm = &Meta{}
		}
		// Compute the merged naming BEFORE StoreObject runs: on a target that already
		// holds this hash, StoreObject rewrites sm.Aliases to the target's, so a union
		// taken afterwards would read the wrong side. A present meta record does NOT
		// prove the object bytes are present and intact (a damaged store), so ALWAYS
		// StoreObject — it (re)writes the object — and only then reassert the union
		// naming, overriding StoreObject's put-oriented merge which would drop the
		// source's aliases.
		tm, terr := target.GetMeta(h)
		var merged *Meta
		if terr == nil && tm != nil {
			merged = unionNaming(tm, sm)
		}
		if _, err := target.StoreObject(d, sm); err != nil {
			fail(err)
		}
		if merged != nil {
			if err := target.SetMeta(h, merged); err != nil {
				fail(err)
			}
		}
	}
	names := make([]string, 0, len(lock.Dependencies))
	for name := range lock.Dependencies {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if _, err := target.Repoint(name, lock.Dependencies[name]); err != nil {
			fail(err)
		}
	}
}

// cmdClone is the one-shot fresh-machine reproduction (#191): hydrate a lock's
// dependency closure from a source, then admit the app source itself under that same
// lock. `hydrate` alone leaves a store its DEPENDENCIES are satisfied in; the obvious
// next command (`oath build <app>`) then fails, because the app is not in the store —
// the lock pins what the app needs, not the app. This composes the two steps whose
// split surfaced as friction, so the postcondition is "a store the app is PRESENT and
// VERIFIED in" — which removes the `no definition named <app>` failure. It does NOT
// promise the app is a buildable ENTRY: whether `build` then accepts it is build's own
// gate (an entry must be entry-shaped and verified), which clone neither weakens nor
// stands in for. The app is verified, not merely stored: clone runs the same
// verifyLock + put the `put --lock` path runs, because a reproduction that skipped the
// proof would defeat the point of reproducing it.
func cmdClone(target *Store, appFile, lockFile, fromDir, remoteURL, keyFile, author string) {
	lock, err := readLock(lockFile)
	if err != nil {
		fail(err)
	}
	// Read the app source ONCE and both verify and admit those exact bytes: a re-read
	// for the put could see a concurrent edit the lock never checked (the `put --lock`
	// discipline).
	src := readSourceFile(appFile)

	// Refuse the canonical corpus and a cloud store FIRST (clearer than the emptiness
	// message), the same hazard hydrate refuses.
	if os.Getenv("OATH_BACKEND") == "cloud" {
		fail(fmt.Errorf("refusing to clone into a cloud-backed store: clone into a local working store (OATH_STORE=$(mktemp -d))"))
	}
	if isCanonicalStore(target.Root) {
		fail(fmt.Errorf("refusing to clone into the canonical corpus %q: clone into a local working store (OATH_STORE=$(mktemp -d)), not the tracked store", target.Root))
	}
	// clone MATERIALIZES a fresh store, so it requires a PRISTINE target — no bindings,
	// no objects, and no repoint policy. That is what makes it a safe SINGLE operation
	// rather than a hydrate-then-put that can half-apply: with nothing already bound, a
	// mid-way failure cannot repoint a name the store had. And a target with a
	// policy.json is a GOVERNED store: clone admits through an in-memory scratch that
	// does not carry the target's rules, so honouring the policy is `put --lock`'s job,
	// not clone's — refuse rather than silently bypass it.
	if len(target.Names()) > 0 || len(target.AllHashes()) > 0 {
		fail(fmt.Errorf("refusing to clone into a non-empty store %q: clone materializes a FRESH store (OATH_STORE=$(mktemp -d)). To add a locked app to an existing store, hydrate then put --lock", target.Root))
	}
	// A policy that cannot be LOADED must fail closed, not fall through the discarded
	// error into the policy-free scratch — that would bypass exactly the rules an
	// ordinary put enforces.
	switch p, err := LoadPolicy(target.Root); {
	case err != nil:
		fail(fmt.Errorf("refusing to clone into %q: its policy.json could not be loaded (%v). Use `hydrate` then `put --lock`", target.Root, err))
	case p != nil:
		fail(fmt.Errorf("refusing to clone into a policy-governed store %q: clone admits through a scratch that does not carry the policy. Use `hydrate` then `put --lock`, which enforce it", target.Root))
	}

	// Do the WHOLE operation in an in-memory scratch, committing to the target only
	// once every definition is accepted — so a VALIDATION failure (a stale lock, an app
	// that will not verify, a multi-definition app whose later form is rejected or
	// falsified) leaves the target UNTOUCHED and a fixed source clones again in place.
	// apiPut stores and repoints each definition as it goes — and repoints even a
	// falsified one — so without the scratch a mid-app failure would leave dependencies
	// and earlier names behind, which the empty-target rule would then make
	// unretryable. The scratch starts empty (the target must be), so nothing is copied
	// in; the source's own bytes are the only thing under test. This is transactional
	// against VALIDATION, not against a mid-COMMIT I/O failure: if a filesystem write
	// fails partway through the copy below, the target can be left partial, the same
	// honest limit as any multi-write on the non-transactional fs store.
	// The scratch's ROOT must be an isolated, empty directory: apiPut below calls
	// LoadPolicy(store.Root), and a relative root like "clone-scratch" would read
	// ./clone-scratch/policy.json from the CURRENT directory — an unrelated file could
	// then block or defer the scratch admission. A fresh temp dir has no policy.json,
	// so the scratch admits policy-free as intended. The mem backend keeps objects in
	// memory; the dir exists only so its (absent) policy resolves to none.
	scratchRoot, err := os.MkdirTemp("", "oath-clone-scratch-")
	if err != nil {
		fail(err)
	}
	defer os.RemoveAll(scratchRoot)
	scratch, err := newStoreWithBackend(newMemBackend(), scratchRoot)
	if err != nil {
		fail(err)
	}
	hydrateLockInto(scratch, lock, fromDir, remoteURL, keyFile, "clone")

	// The deps are present in scratch now, so the app's external set resolves.
	// verifyLock pins it to the lock exactly (same names, same hashes).
	if err := verifyLock(scratch, src, lock); err != nil {
		fail(err)
	}

	// Admit + verify the app IN SCRATCH. apiPut (not cmdPutSrc) so the per-definition
	// RESULTS are in hand: clone's postcondition is that the app is BUILDABLE, and a
	// clean put exit is not proof of that — it exits 0 on a blocked or pending outcome.
	results, perr := apiPut(scratch, src, author, "")
	report := renderPutReports(results)
	if perr != nil {
		fmt.Print(report)
		fail(perr)
	}
	if len(results) == 0 {
		fail(fmt.Errorf("the app source %s declares no definitions — there is nothing to build", appFile))
	}
	// Every declaration must be ACCEPTED — any other outcome fails with the target
	// UNTOUCHED, so a fixed source clones again in place.
	for _, rep := range results {
		if rep.Status != "accepted" {
			fmt.Print(report)
			fail(fmt.Errorf("clone did not admit %q (%s); the target is unchanged — fix the source and clone again", rep.Name, rep.Status))
		}
	}
	// And each name must be bound in scratch to the object this put produced — not
	// merely resolve, which a redeclared DEPENDENCY name would still do against the
	// hydrated hash. A source may redeclare its OWN name across several forms (last
	// wins), so the store is compared only against the LAST accepted report for each
	// name, never an earlier superseded one.
	lastHash := make(map[string]string, len(results))
	for _, rep := range results {
		lastHash[rep.Name] = rep.Hash
	}
	for name, want := range lastHash {
		if h, ok := scratch.Resolve(name); !ok || h != want {
			fail(fmt.Errorf("clone reported %q accepted at #%s but scratch binds it to #%s — not buildable", name, shortHash(want), shortHash(h)))
		}
	}

	// Everything verified in scratch. COMMIT to the target: objects and names, then the
	// journal entries apiPut recorded (hydration does not journal). AppendLog re-chains
	// onto the target's empty journal, so the audit trail survives the reproduction.
	if err := copyStore(scratch, target); err != nil {
		fail(err)
	}
	for _, e := range scratch.ReadLog() {
		entry := e
		if err := target.AppendLog(&entry); err != nil {
			fail(err)
		}
	}
	fmt.Printf("cloned %d dependency object(s) from the source; admitted %s:\n", len(lock.Closure), appFile)
	fmt.Print(report)
}

// unionNaming reproduces src's naming onto the object the target already holds,
// losing no name from either side. The NAMING is authoritative from the SOURCE,
// because the lock was authored against it: a name the lock binds must carry the
// source's vocabulary or the consumer's constructors fail to resolve (FindCtor reads
// a constructor through the BOUND name's own naming block — m.CtorNames when it is
// the primary name, else m.Aliases[name]). So src's primary name and aliases win on
// any conflict; the target's own names are folded in as additional aliases, so
// nothing the target could already resolve is lost. VERDICT fields are facts about
// the hash, not the name — the target's are kept, matching StoreObject's convention
// of not downgrading an object the store already verified.
func unionNaming(target, src *Meta) *Meta {
	out := *target // keep the target's verdict fields (hash-facts)
	// Naming from the source, wholesale.
	out.Name = src.Name
	out.TyVarNames, out.CtorNames = src.TyVarNames, src.CtorNames
	out.PropNames, out.ParamNames = src.PropNames, src.ParamNames
	out.Aliases = make(map[string]*AliasNaming, len(src.Aliases)+len(target.Aliases)+1)
	for k, v := range src.Aliases {
		out.Aliases[k] = v
	}
	// Fold the target's prior naming in as aliases WITHOUT overwriting the source's —
	// the source has already won every conflict above.
	add := func(name string, an *AliasNaming) {
		if name == "" || name == out.Name {
			return
		}
		if _, ok := out.Aliases[name]; !ok {
			out.Aliases[name] = an
		}
	}
	add(target.Name, &AliasNaming{TyVarNames: target.TyVarNames, CtorNames: target.CtorNames, PropNames: target.PropNames, ParamNames: target.ParamNames})
	for name, an := range target.Aliases {
		add(name, an)
	}
	if len(out.Aliases) == 0 {
		out.Aliases = nil
	}
	return &out
}

// hydrateFetchLabel names a closure hash for a fetch error. A bare 12-hex string is
// not a diagnosis: on a drifted registry a consumer would have to grep the lock to
// learn WHICH dependency is missing. The lock already binds names to hashes, so this
// returns the binding name when there is one, and says plainly when the hash is a
// transitive object the lock lists in the closure but binds no name to.
func hydrateFetchLabel(lock oathLock, h string) string {
	// Collect EVERY dependency name binding this hash, not the first Go's map
	// iteration happens to yield: same-hash aliases are supported, so a bare
	// first-match would name a different alias run to run and omit the others.
	var names []string
	for name, dh := range lock.Dependencies {
		if dh == h {
			names = append(names, name)
		}
	}
	if len(names) > 0 {
		sort.Strings(names)
		return fmt.Sprintf("%s (#%s)", strings.Join(names, "/"), shortHash(h))
	}
	return fmt.Sprintf("transitive object #%s (the lock lists it in the closure but binds no name to it)", shortHash(h))
}

func writeLock(path string, lock oathLock) error {
	b, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func readLock(path string) (oathLock, error) {
	var lock oathLock
	b, err := os.ReadFile(path)
	if err != nil {
		return lock, err
	}
	if err := json.Unmarshal(b, &lock); err != nil {
		return lock, fmt.Errorf("corrupt lockfile %s: %w", path, err)
	}
	if lock.Format != oathLockFormat {
		return lock, fmt.Errorf("lockfile %s has format %q, expected %q", path, lock.Format, oathLockFormat)
	}
	return lock, nil
}

// verifyLock is the guard `oath put --lock` runs BEFORE elaborating. The lock must
// be a COMPLETE and CURRENT specification of the source's external dependencies: it
// recomputes the source's external set against the target store and requires an
// EXACT match — same names, same hashes. That catches all three failure modes a
// weaker check would miss: a repointed dependency (a name now binds a different
// object), a stale lock (the source gained or lost a dependency since it was
// generated), and a lock written for a different file. Any of them would otherwise
// let elaboration silently resolve a name against the ambient store.
func verifyLock(st *Store, src string, lock oathLock) error {
	direct, _, err := externalClosure(st, src)
	if err != nil {
		return fmt.Errorf("the store cannot resolve this file's dependencies: %w", err)
	}
	var problems []string
	for name, h := range direct {
		switch lh, ok := lock.Dependencies[name]; {
		case !ok:
			problems = append(problems, fmt.Sprintf("  %-18s referenced by the source but ABSENT from the lock (stale lock?)", name))
		case lh != h:
			problems = append(problems, fmt.Sprintf("  %-18s resolves to #%s, but the lock pins #%s", name, shortHash(h), shortHash(lh)))
		}
	}
	for name := range lock.Dependencies {
		if _, ok := direct[name]; !ok {
			problems = append(problems, fmt.Sprintf("  %-18s pinned by the lock but NOT referenced by the source (stale lock?)", name))
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return fmt.Errorf("lock does not match the source's dependencies in this store:\n%s\n"+
			"run `oath resolve` to regenerate the lock, or restore the pinned objects", strings.Join(problems, "\n"))
	}
	return nil
}

// cmdResolve computes a source file's external dependency set and writes a
// lockfile. With --from <store> or --remote <url> it also FETCHES the closure into
// the target store and binds the direct external names, so the file can then be put
// into a store that did not already hold its dependencies. Elaboration always runs
// in a scratch in-memory store; the target is written only after it succeeds.
func cmdResolve(target *Store, file, fromDir, remoteURL, keyFile, out string) {
	src := readSourceFile(file)
	fetching := fromDir != "" || remoteURL != ""
	if fetching {
		// Fetching WRITES objects and names into the target. Refuse anything but a
		// local working store: the canonical corpus must not be polluted
		// (guardNewNames's principle), and a cloud store is shared, so a resolve into
		// it would bypass gates and journalling.
		if os.Getenv("OATH_BACKEND") == "cloud" {
			fail(fmt.Errorf("refusing to resolve into a cloud-backed store: fetch into a local working store (OATH_STORE=$(mktemp -d))"))
		}
		if isCanonicalStore(target.Root) {
			fail(fmt.Errorf("refusing to fetch dependencies into the canonical corpus %q: resolve into a local working store (OATH_STORE=$(mktemp -d)), not the tracked store", target.Root))
		}
	}

	// The elaboration store resolves every dependency: seeded from a local source,
	// or fetching on demand from a registry.
	elab, err := newStoreWithBackend(newMemBackend(), "resolve-scratch")
	if err != nil {
		fail(err)
	}
	fetchErr := func() error { return nil }
	switch {
	case remoteURL != "":
		signer, err := resolveSigner(keyFile, "")
		if err != nil {
			fail(fmt.Errorf("oath resolve --remote authenticates every read; pass --key <file>: %w", err))
		}
		clientSigner = signer
		elab.fetcher, fetchErr = registryFetcher(remoteURL, signer, elab)
	case fromDir != "":
		// Explicit FILESYSTEM backend: OpenStore honours OATH_BACKEND, so on a
		// cloud-tagged binary `--from /local/store` would read the cloud store.
		be, err := openFSBackend(fromDir)
		if err != nil {
			fail(err)
		}
		fromStore, err := newStoreWithBackend(be, fromDir)
		if err != nil {
			fail(err)
		}
		if err := copyStore(fromStore, elab); err != nil {
			fail(err)
		}
	default:
		// No source given: resolve against the target itself (deps already local).
		if err := copyStore(target, elab); err != nil {
			fail(err)
		}
	}

	direct, closure, err := computeExternal(elab, src)
	if err != nil {
		// A registry fetch failure (auth, missing `object` tool, content-address
		// mismatch, a dependency that does not typecheck) is the real cause behind an
		// "unknown name" here — surface it rather than the elaboration symptom.
		if fe := fetchErr(); fe != nil {
			fail(fmt.Errorf("resolving from the registry: %w", fe))
		}
		fail(err)
	}
	if fetching {
		for _, h := range closure {
			d, err := elab.GetDef(h)
			if err != nil {
				fail(fmt.Errorf("fetching #%s: %w", shortHash(h), err))
			}
			m, _ := elab.GetMeta(h)
			if m == nil {
				m = &Meta{}
			}
			if _, err := target.StoreObject(d, m); err != nil {
				fail(err)
			}
		}
		for name, h := range direct {
			if _, err := target.Repoint(name, h); err != nil {
				fail(err)
			}
		}
	}
	if out == "" {
		out = file + ".lock"
	}
	if err := writeLock(out, oathLock{Format: oathLockFormat, File: file, Dependencies: direct, Closure: closure}); err != nil {
		fail(err)
	}
	verb := "resolved"
	if fetching {
		verb = "resolved and fetched"
	}
	fmt.Printf("%s %d external name(s) across %d object(s) in the closure -> %s\n", verb, len(direct), len(closure), out)
}
