package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// #187: authoring-layer dependency resolution, entirely OUTSIDE identity. A .oath
// source references bare names that resolve against whatever ambient store is
// active at put time, with a late/silent failure. `oath resolve` records the
// intention — which external names, at which hashes — in a lockfile, and
// `oath put --lock` verifies the store against it BEFORE elaborating, turning the
// ambient binding into a checked one. Nothing here changes what a Def hashes to:
// the lock guards resolution, it never participates in it.

const oathLockFormat = "oath-lock/1"

// oathLock is the resolved dependency manifest for one source file. Dependencies
// are the DIRECT external names the source references (checked by name at
// put --lock); Closure is the full transitive object closure (fetched so
// elaboration can typecheck). It is generated by `oath resolve` and may be edited
// by hand to pin or disambiguate.
type oathLock struct {
	Format       string            `json:"format"`
	File         string            `json:"file"`
	Dependencies map[string]string `json:"dependencies"` // direct external name -> hash
	Closure      []string          `json:"closure"`      // transitive object hashes, sorted
}

// seedStore is a throwaway IN-MEMORY copy of `from`, so a batch can be elaborated
// (with its same-batch references resolving) without mutating the source store. It
// is explicitly memory-backed rather than OpenStore(dir): OpenStore honours
// OATH_BACKEND, so on a cloud-tagged binary a scratch store would silently BE the
// real cloud store, and elaboration would write objects and repoint names into it
// bypassing every gate. In-memory also needs no temp directory to clean up.
func seedStore(from *Store) (*Store, error) {
	tmp, err := newStoreWithBackend(newMemBackend(), "resolve-scratch")
	if err != nil {
		return nil, err
	}
	for _, h := range from.AllHashes() {
		d, err := from.GetDef(h)
		if err != nil {
			continue
		}
		m, _ := from.GetMeta(h)
		if m == nil {
			m = &Meta{}
		}
		if _, err := tmp.StoreObject(d, m); err != nil {
			return nil, err
		}
	}
	for name, h := range from.Names() {
		if _, err := tmp.Repoint(name, h); err != nil {
			return nil, err
		}
	}
	return tmp, nil
}

// elaborateInto elaborates each top-level form against tmp (ELABORATION ONLY — no
// verification, no journalling) in order, storing each so a later same-batch form
// can resolve it. It returns the batch's object hashes and the DIRECT EXTERNAL
// dependencies (surface name -> hash).
//
// The external classification is per resolution and by PRIOR-BATCH HASH, which is
// what makes it correct on two edge cases a coarser rule misses. A name is external
// for a form iff it resolved to a hash NO EARLIER FORM produced — so an early form's
// reference to an ambient `foo` is captured as external even when a later form
// redeclares `foo` (order-dependent shadowing), and a reference to a prior form is
// same-batch even when that form is byte-identical to an external definition (a hash
// collision). Names are captured (not reconstructed from hashes) because Resolve and
// FindCtor both log the surface name the source actually used.
func elaborateInto(tmp *Store, src string) (map[string]string, error) {
	forms, err := parseForms(src)
	if err != nil {
		return nil, err
	}
	priorNames := map[string]bool{} // names DECLARED by earlier forms in this batch
	external := map[string]string{} // direct external dependency: surface name -> hash
	for _, f := range forms {
		if f.K != "list" || len(f.Kids) == 0 {
			return nil, fmt.Errorf("top-level form must be (defn ...) or (data ...)")
		}
		tmp.resolveLog = map[string]string{}
		var d *Def
		var m *Meta
		switch {
		case f.Kids[0].isSym("defn"):
			d, m, err = elabFunc(tmp, f)
		case f.Kids[0].isSym("data"):
			d, m, err = elabData(tmp, f)
		default:
			tmp.resolveLog = nil
			return nil, fmt.Errorf("top-level form must be (defn ...) or (data ...), got %q", f.Kids[0].Sym)
		}
		logged := tmp.resolveLog
		tmp.resolveLog = nil
		if err != nil {
			return nil, err
		}
		// A resolution is EXTERNAL iff its surface name was not declared by an
		// EARLIER form. By NAME, not by hash: a name is a same-batch reference only
		// when this batch bound it first, regardless of whether the object it
		// resolves to happens to equal an ambient definition under another name
		// (structurally identical aliases are supported, CLAUDE.md). Order matters —
		// an early reference to an ambient `foo` stays external even if a later form
		// redeclares `foo`.
		for name, rh := range logged {
			if !priorNames[name] {
				external[name] = rh
			}
		}
		h, err := tmp.StoreObject(d, m)
		if err != nil {
			return nil, err
		}
		if m.Name != "" {
			priorNames[m.Name] = true
			for _, cn := range m.CtorNames { // a data form also declares its constructors
				priorNames[cn] = true
			}
			if _, err := tmp.Repoint(m.Name, h); err != nil {
				return nil, err
			}
		}
	}
	return external, nil
}

// externalClosure elaborates src against `from` (which must hold its dependencies)
// and returns the direct external dependencies (surface name -> hash) plus the full
// transitive object closure of those hashes (so a fresh store can typecheck them).
func externalClosure(from *Store, src string) (map[string]string, []string, error) {
	tmp, err := seedStore(from)
	if err != nil {
		return nil, nil, err
	}
	direct, err := elaborateInto(tmp, src)
	if err != nil {
		return nil, nil, err
	}
	// Transitive closure of the direct external hashes. No batch exclusion: the
	// roots are external NAMES, whose closures lie entirely in `from`, so a batch
	// object is never reached — and a direct external whose hash happens to equal a
	// later batch form's is still fetched, as it must be for an earlier reference.
	closure := map[string]bool{}
	var visit func(string)
	visit = func(h string) {
		if closure[h] {
			return
		}
		closure[h] = true
		d, err := tmp.GetDef(h)
		if err != nil {
			return
		}
		for dep := range collectDeps(d) {
			visit(dep)
		}
	}
	for _, h := range direct {
		visit(h)
	}
	hs := make([]string, 0, len(closure))
	for h := range closure {
		hs = append(hs, h)
	}
	sort.Strings(hs)
	return direct, hs, nil
}

func writeLock(path string, lock oathLock) error {
	b, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func readLock(path string) (oathLock, error) {
	var lock oathLock
	b, err := os.ReadFile(path)
	if err != nil {
		return lock, err
	}
	if err := json.Unmarshal(b, &lock); err != nil {
		return lock, fmt.Errorf("corrupt lockfile %s: %w", path, err)
	}
	if lock.Format != oathLockFormat {
		return lock, fmt.Errorf("lockfile %s has format %q, expected %q", path, lock.Format, oathLockFormat)
	}
	return lock, nil
}

// verifyLock is the guard `oath put --lock` runs BEFORE elaborating. The lock must
// be a COMPLETE and CURRENT specification of the source's external dependencies: it
// recomputes the source's external set against the target store and requires an
// EXACT match — same names, same hashes. That catches all three failure modes a
// weaker check would miss: a repointed dependency (a name now binds a different
// object), a stale lock (the source gained or lost a dependency since it was
// generated), and a lock written for a different file. Any of them would otherwise
// let elaboration silently resolve a name against the ambient store.
func verifyLock(st *Store, src string, lock oathLock) error {
	direct, _, err := externalClosure(st, src)
	if err != nil {
		return fmt.Errorf("the store cannot resolve this file's dependencies: %w", err)
	}
	var problems []string
	for name, h := range direct {
		switch lh, ok := lock.Dependencies[name]; {
		case !ok:
			problems = append(problems, fmt.Sprintf("  %-18s referenced by the source but ABSENT from the lock (stale lock?)", name))
		case lh != h:
			problems = append(problems, fmt.Sprintf("  %-18s resolves to #%s, but the lock pins #%s", name, shortHash(h), shortHash(lh)))
		}
	}
	for name := range lock.Dependencies {
		if _, ok := direct[name]; !ok {
			problems = append(problems, fmt.Sprintf("  %-18s pinned by the lock but NOT referenced by the source (stale lock?)", name))
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return fmt.Errorf("lock does not match the source's dependencies in this store:\n%s\n"+
			"run `oath resolve` to regenerate the lock, or restore the pinned objects", strings.Join(problems, "\n"))
	}
	return nil
}

// cmdResolve computes a source file's external dependency set and writes a
// lockfile. With --from <store>, it also FETCHES the closure objects into the
// target store and binds the direct external names, so the file can then be put
// into a store that did not already hold its dependencies.
func cmdResolve(target *Store, file, fromDir, out string) {
	src := readSourceFile(file)
	from := target
	if fromDir != "" {
		// Fetching WRITES the dependency objects and names into the target. Refuse a
		// target that is not a local working store: the canonical corpus must not be
		// polluted (guardNewNames's principle), and a cloud store is shared, so a
		// resolve into it would bypass gates and journalling.
		if os.Getenv("OATH_BACKEND") == "cloud" {
			fail(fmt.Errorf("refusing to resolve --from into a cloud-backed store: fetch into a local working store (OATH_STORE=$(mktemp -d))"))
		}
		if isCanonicalStore(target.Root) {
			fail(fmt.Errorf("refusing to fetch dependencies into the canonical corpus %q: resolve into a local working store (OATH_STORE=$(mktemp -d)), not the tracked store", target.Root))
		}
		// Open --from with an explicit FILESYSTEM backend: OpenStore honours
		// OATH_BACKEND, so on a cloud-tagged binary `--from /local/store` would
		// silently read the cloud store instead of the directory named.
		be, err := openFSBackend(fromDir)
		if err != nil {
			fail(err)
		}
		f, err := newStoreWithBackend(be, fromDir)
		if err != nil {
			fail(err)
		}
		from = f
	}
	direct, closure, err := externalClosure(from, src)
	if err != nil {
		fail(err)
	}
	if fromDir != "" {
		for _, h := range closure {
			d, err := from.GetDef(h)
			if err != nil {
				fail(fmt.Errorf("fetching #%s: %w", shortHash(h), err))
			}
			m, _ := from.GetMeta(h)
			if m == nil {
				m = &Meta{}
			}
			if _, err := target.StoreObject(d, m); err != nil {
				fail(err)
			}
		}
		for name, h := range direct {
			if _, err := target.Repoint(name, h); err != nil {
				fail(err)
			}
		}
	}
	if out == "" {
		out = file + ".lock"
	}
	if err := writeLock(out, oathLock{Format: oathLockFormat, File: file, Dependencies: direct, Closure: closure}); err != nil {
		fail(err)
	}
	verb := "resolved"
	if fromDir != "" {
		verb = "resolved and fetched"
	}
	fmt.Printf("%s %d external name(s) across %d object(s) in the closure -> %s\n", verb, len(direct), len(closure), out)
}
